import {StyleSheet} from 'react-native';

export const homeScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 16,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  profileButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
  },
  profileButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  noteList: {
    flex: 1,
    paddingTop: 8,
  },
  noteListContent: {
    paddingBottom: 50,
  },
  noteItem: {
    margin: 10,
    marginTop: 6,
    marginBottom: 8,
    padding: 15,
    borderRadius: 16,
    elevation: 2,
  },
  noteTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 8,
  },
  noteContent: {
    fontSize: 14,
    marginBottom: 8,
    lineHeight: 20,
  },
  noteTime: {
    fontSize: 12,
    fontStyle: 'italic',
  },
  addButton: {
    position: 'absolute',
    right: 30,
    bottom: 30,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
  },
  addButtonText: {
    fontSize: 32,
    color: 'white',
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: {width: 1, height: 1},
    textShadowRadius: 2,
  },
  searchContainer: {
    padding: 15,
    paddingBottom: 8,
  },
  searchInput: {
    borderWidth: 1.5,
    borderRadius: 20,
    padding: 12,
    paddingLeft: 20,
    fontSize: 15,
  },
  tipContainer: {
    padding: 6,
    paddingTop: 4,
    paddingLeft: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    alignSelf: 'center',
    width: '90%',
  },
  tipText: {
    fontSize: 12,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  sortMenu: {
    marginTop: 8,
    position: 'relative',
    alignSelf: 'flex-end',
    marginRight: 4,
  },
  sortMenuButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  sortMenuButtonText: {
    fontSize: 14,
    fontWeight: '500',
    marginRight: 8,
  },
  sortMenuArrow: {
    fontSize: 12,
    marginLeft: 4,
  },
  sortMenuContent: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: 4,
    borderRadius: 12,
    padding: 12,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    zIndex: 1000,
    minWidth: 160,
  },
  sortMenuSection: {
    marginBottom: 8,
  },
  sortMenuTitle: {
    fontSize: 12,
    marginBottom: 4,
    paddingHorizontal: 8,
  },
  sortMenuItem: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  sortMenuItemText: {
    fontSize: 14,
  },
  notePreviewImage: {
    width: '100%',
    height: 120,
    borderRadius: 8,
    marginVertical: 8,
  },
  profileImage: {
    width: '100%',
    height: '100%',
    borderRadius: 18,
  },
  loadingContainer: {
    padding: 6,
    paddingTop: 4,
    paddingLeft: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 4,
    alignSelf: 'center',
    width: '90%',
  },
  loadingText: {
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 14,
    textAlign: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
});
