name: React Native Build Android Release

on: workflow_dispatch

jobs:
  build_android:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
        with:
          repository: xyr723/CloudNote
          token: ${{ secrets.MIMIR_GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install Yarn
        run: |
          npm install -g yarn

      - name: Install dependencies
        run: |
          yarn install
          npx react-native clean
          yarn android

      - name: Install JDK 18
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Install Android SDK and NDK
        run: |
          # 安装必需的工具和依赖
          sudo apt update
          sudo apt install -y wget unzip openjdk-18-jdk

          # 下载并解压 Android 命令行工具
          wget https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          unzip commandlinetools-linux-6609375_latest.zip -d $HOME/android-sdk

          # 同意 SDK 许可协议
          yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses

          # 安装必要的 Android SDK 组件
          $HOME/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;21.4.7075529"

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_apk
        with:
          releaseDirectory: android/app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.APK_SIGN_JKS_BASE64 }}
          keyStorePassword: ${{ secrets.APK_SIGN_JKS_PASSWORD }}
          keyPassword: ${{ secrets.APK_SIGN_ALIAS_PASS }}
          alias: ${{ secrets.APK_SIGN_ALIAS }}
        env:
          BUILD_TOOLS_VERSION: '34.0.0'

      - name: Publish Android Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-release
          path: android/app/build/outputs/apk/release/*-release.apk
